#!/usr/bin/env bash
#
# Install (or uninstall) the excalidraw-screenshot-connector LaunchAgents on macOS.
#
# Generates filled-in plists from your .env + detected tool paths, installs them
# to ~/Library/LaunchAgents, and (re)loads them. Idempotent — re-run anytime.
#
#   ./install.sh              install / reload (gateway + ngrok tunnel)
#   ./install.sh --uninstall  stop and remove both agents
#
# Opt-in keep-awake (prevents the Mac sleeping out the tunnel):
#   CAFFEINATE=1 ./install.sh
#
# This is a native FastMCP server (one tool, no backend) that drives a headless
# Chromium via Playwright — so it needs your GUI/login session and a one-time
# browser download (handled below). No Full Disk Access required.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LA_DIR="$HOME/Library/LaunchAgents"
GATEWAY_LABEL="excalidraw-screenshot-connector"
NGROK_LABEL="excalidraw-screenshot-connector-ngrok"
GATEWAY_PLIST="$LA_DIR/$GATEWAY_LABEL.plist"
NGROK_PLIST="$LA_DIR/$NGROK_LABEL.plist"

bootout() {  # bootout a label and wait until it's fully gone (avoids bootstrap race)
  local label="$1" i
  if launchctl print "gui/$(id -u)/$label" >/dev/null 2>&1; then
    launchctl bootout "gui/$(id -u)/$label" 2>/dev/null || true
  fi
  for i in $(seq 1 50); do
    launchctl print "gui/$(id -u)/$label" >/dev/null 2>&1 || return 0
    sleep 0.2
  done
}

if [[ "${1:-}" == "--uninstall" ]]; then
  bootout "$NGROK_LABEL"
  bootout "$GATEWAY_LABEL"
  rm -f "$GATEWAY_PLIST" "$NGROK_PLIST"
  echo "Uninstalled. Your .env and repo are untouched."
  exit 0
fi

# --- Load and validate config ---------------------------------------------
[[ -f "$SCRIPT_DIR/.env" ]] || {
  echo "ERROR: $SCRIPT_DIR/.env not found. Copy .env.example to .env and fill it in." >&2
  exit 1
}
set -a; source "$SCRIPT_DIR/.env"; set +a

: "${PUBLIC_URL:?must be set in .env}"
: "${GOOGLE_CLIENT_ID:?must be set in .env}"
: "${GOOGLE_CLIENT_SECRET:?must be set in .env}"
if [[ -z "${ALLOWED_EMAILS:-}" ]]; then
  echo "ERROR: set ALLOWED_EMAILS in .env (fail closed)." >&2
  exit 1
fi

# --- Detect tools ----------------------------------------------------------
UV_BIN="$(command -v uv || true)"
[[ -n "$UV_BIN" ]] || { echo "ERROR: 'uv' not found on PATH." >&2; exit 1; }
NGROK_BIN="$(command -v ngrok || true)"
[[ -n "$NGROK_BIN" ]] || { echo "ERROR: 'ngrok' not found on PATH." >&2; exit 1; }

PORT="${PORT:-8040}"
TOOL_PATH="$(dirname "$UV_BIN"):/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin"
NGROK_PATH="$(dirname "$NGROK_BIN"):/usr/bin:/bin:/usr/sbin:/sbin"

# --- One-time: install the Chromium that matches server.py's resolved env ---
echo "Ensuring Playwright Chromium is installed (matching server.py's env)…"
( cd "$SCRIPT_DIR" && "$UV_BIN" run server.py --install-browsers >/dev/null 2>&1 ) \
  || { echo "ERROR: failed to install Playwright Chromium. Run: uv run server.py --install-browsers" >&2; exit 1; }

# --- Helpers to build the plist EnvironmentVariables block -----------------
xml()  { printf '%s' "$1" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g'; }
pair() { printf '        <key>%s</key>\n        <string>%s</string>' "$1" "$(xml "$2")"; }

ENV_BLOCK="$(pair PUBLIC_URL "$PUBLIC_URL")"
ENV_BLOCK+=$'\n'"$(pair GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID")"
ENV_BLOCK+=$'\n'"$(pair GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET")"
ENV_BLOCK+=$'\n'"$(pair ALLOWED_EMAILS "$ALLOWED_EMAILS")"
[[ -n "${ROOM_SYNC_MS:-}"    ]] && ENV_BLOCK+=$'\n'"$(pair ROOM_SYNC_MS "$ROOM_SYNC_MS")"
[[ -n "${HOST:-}"            ]] && ENV_BLOCK+=$'\n'"$(pair HOST "$HOST")"
ENV_BLOCK+=$'\n'"$(pair PORT "$PORT")"
[[ -n "${EMAIL_CLAIM:-}"     ]] && ENV_BLOCK+=$'\n'"$(pair EMAIL_CLAIM "$EMAIL_CLAIM")"
[[ -n "${DEBUG:-}"           ]] && ENV_BLOCK+=$'\n'"$(pair DEBUG "$DEBUG")"
[[ -n "${JWT_SIGNING_KEY:-}" ]] && ENV_BLOCK+=$'\n'"$(pair JWT_SIGNING_KEY "$JWT_SIGNING_KEY")"
[[ -n "${ALLOWED_REDIRECT_URI_PATTERNS:-}" ]] && ENV_BLOCK+=$'\n'"$(pair ALLOWED_REDIRECT_URI_PATTERNS "$ALLOWED_REDIRECT_URI_PATTERNS")"
ENV_BLOCK+=$'\n'"$(pair PATH "$TOOL_PATH")"

CAFF_ARGS=""
if [[ "${CAFFEINATE:-}" == "1" ]]; then
  CAFF_ARGS=$'        <string>/usr/bin/caffeinate</string>\n        <string>-i</string>\n'
fi

mkdir -p "$LA_DIR"

# --- Gateway plist (contains secrets → 0600) -------------------------------
cat > "$GATEWAY_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by install.sh — do not edit by hand; edit .env and re-run. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$GATEWAY_LABEL</string>
    <key>ProgramArguments</key>
    <array>
$CAFF_ARGS        <string>$UV_BIN</string>
        <string>run</string>
        <string>$SCRIPT_DIR/server.py</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
$ENV_BLOCK
    </dict>
    <key>WorkingDirectory</key>
    <string>$SCRIPT_DIR</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/$GATEWAY_LABEL.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/$GATEWAY_LABEL.err</string>
</dict>
</plist>
PLIST
chmod 600 "$GATEWAY_PLIST"

# --- ngrok plist -----------------------------------------------------------
cat > "$NGROK_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by install.sh — do not edit by hand; edit .env and re-run. -->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$NGROK_LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$NGROK_BIN</string>
        <string>http</string>
        <string>--url=$PUBLIC_URL</string>
        <string>$PORT</string>
    </array>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>$NGROK_PATH</string>
    </dict>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/tmp/$NGROK_LABEL.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/$NGROK_LABEL.err</string>
</dict>
</plist>
PLIST

# --- (Re)load (gateway first, then tunnel) ---------------------------------
bootout "$NGROK_LABEL"
bootout "$GATEWAY_LABEL"
launchctl bootstrap "gui/$(id -u)" "$GATEWAY_PLIST"
launchctl bootstrap "gui/$(id -u)" "$NGROK_PLIST"

cat <<DONE

Installed and loaded:
  $GATEWAY_PLIST  (FastMCP screenshot server on 127.0.0.1:$PORT)
  $NGROK_PLIST

Public URL : $PUBLIC_URL/mcp
Inspect    : launchctl print gui/$(id -u)/$GATEWAY_LABEL | grep -i state
Logs       : tail -f /tmp/$GATEWAY_LABEL.log /tmp/$NGROK_LABEL.log
Uninstall  : $SCRIPT_DIR/install.sh --uninstall
DONE
